name: precip_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - requests
  - cartopy
  - matplotlib
  - numpy
  - pandas
  - scipy
  - pyproj
  - xarray
  - netcdf4
  - h5netcdf
  - cfgrib
  - cmocean
  - pyextremes
  - metpy
